// Rewrite the instructions in your own words


// Write the objectives and the tests

// Write the pseudocode
/* variable email 
var ._order and var _order@
in email store the user email

*/



// paste your JS generated by blockly below here
var email, __order, __order2;


email = window.prompt('Enter your email');
__order = email.indexOf('@') + 1;
__order2 = email.lastIndexOf('.') + 1;
if (__order == 0) {
  window.alert('Invalid');
} else if (__order == 1) {
  window.alert('Invalid');
} else if (__order2 == 0) {
  window.alert('Invalid');
} else if (__order2 == 1) {
  window.alert('Invalid');
} else if (__order2 < __order) {
  window.alert('Invalid');
} else if (__order2 == email.length) {
  window.alert('Invalid');
} else if (__order == email.length) {
  window.alert('Invalid');
} else {
  window.alert('valid');
}