// Rewrite the instructions in your own words
/*First the program should ask a phrase for the user
*then it should print the acronym of the phrase by taking the
*first letters
*
*

// Write the objectives and the tests
//The objective is to print the acronym

// Write the pseudocode
/*create a variable to store the string of the user
*we need a variable to store a length of the text of the user
*we need a for loop over the all the text
*while looping it should take the first letter of the word in the
*text or phrase. And it should store in a variable acronym.
*

*

*/



// paste your JS generated by blockly below here
var acronym, anyString, i;


acronym = '';
anyString = window.prompt('Enter your text').split(' ');
for (var i_index in anyString) {
  i = anyString[i_index];
  acronym += String(i.charAt(0));
}
window.alert(acronym.toUpperCase());