// Rewrite the instructions in your own words
/*
*Basically the program is play a game with the user
*rock paper scissors 
*for example if the user knows 2 of 3 he win else fail

*/

// Write the objectives and the tests

// Write the pseudocode
 /*
* I will create a variable to store my list of words (rock paper scissors)
*variable to store the word selected randomly by the computer
*variable to store the 

 */


// paste your JS generated by blockly below here
var listOfWords, win, loss, selecte_by_computer, win_message, input, looser_mass;

function mathRandomInt(a, b) {
  if (a > b) {
    // Swap a and b to ensure a is smaller.
    var c = a;
    a = b;
    b = c;
  }
  return Math.floor(Math.random() * (b - a + 1) + a);
}


listOfWords = ''.split('Rock,Scissor, Paper');
win = 0;
loss = 0;
for (var count = 0; count < 3; count++) {
  selecte_by_computer = listOfWords[(mathRandomInt(1, 3) - 1)];
  input = window.prompt('Play');
  if (selecte_by_computer == input) {
    win = (typeof win == 'number' ? win : 0) + 1;
  } else {
    loss = (typeof loss == 'number' ? loss : 0) + 1;
  }
}
win_message = 'you win';
looser_mass = 'you loose';
if (win > loss) {
  window.alert(win_message - win);
} else {
  window.alert(looser_mass);
}